import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
//参考URL：パラメータ送付https://qiita.com/syu_ikeda/items/52fbe7480b2b9a54db0c
import { useRouter } from 'next/router';

import styles from '../styles/Home.module.css'
//import SyntaxHighlighter from 'react-syntax-highlighter';
//import { monokaiSublime } from "react-syntax-highlighter/dist/cjs/styles/hljs";



export default function Home() {
  const [examtitle, setText] = useState(null)
  const [examid, setId] = useState(null)
  const [choice, setChoices] = useState(null)
  const [choice_question, setChoice_question] = useState(null)

  useEffect((ids) => {
    ids = Math.floor(Math.random() * 5)//ランダム表示

    fetch('/api/questions_sample/')
      .then(res => res.json())
      .then(data => {

        setText(data[ids].question_txt)
        setId(data[ids].id)
      })

    fetch('/api/choices/')
      .then(res => res.json())
      .then(data => {
        var choi = document.getElementById('choice');
        
        const choice_set = data.filter(el => el.question_id === ids +1)
        setChoice_question(choice_set[0].question_id)
        choi.insertAdjacentHTML('beforeend',choice_set[0].question_id + '<br/>')
        //配列フィルター参考URL：https://www.digitalocean.com/community/tutorials/js-array-search-methods-ja
        for (let i= 0; i <choice_set.length; i++){
          setChoices(choice_set[i].display_name)
          choi.insertAdjacentHTML('beforeend',choice_set[i].display_name + '<br/>')
        }
        
        
      })
    


  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js PostgreSQL
        </h1>

        <p className={styles.description}>
          Next.js上でpostgresqlからデータ取得し、表示する例 <br />
          
          


        </p>

        <div>
          <div id="queston">問題：{examid} <br /> {examtitle} <br /></div>
          <div id="choice">選択肢<br />
          
          </div>
          <br />
          <input type="radio" name="answer" value="1" ></input><label>ア</label><br />
          <input type="radio" name="answer" value="2" ></input><label>イ</label><br />
          <input type="radio" name="answer" value="3" ></input><label>ウ</label><br />
          <input type="radio" name="answer" value="4" ></input><label>エ</label><br />
          <button type="button" >回答</button>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright 2021 m_sawada
        </a>
      </footer>
    </div >
  )
}