import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
//import SyntaxHighlighter from 'react-syntax-highlighter';
//import { monokaiSublime } from "react-syntax-highlighter/dist/cjs/styles/hljs";



export default function Home() {
  const [examtitle, setText] = useState(null)
  const [examid, setId] = useState(null)
  const [choice, setChoices] = useState(null)
  useEffect((id) => {
    id = Math.floor(Math.random() * data.length)//ランダム表示

    fetch('/api/questions_sample/'+sql_str)
      .then(res => res.json())
      .then(data => {

        setText(data[id].question_txt)
        setId(data[id].id)
      })

    fetch('/api/choices')
      .then(res => res.json())
      .then(data => {
        setChoices(data[id].choice_txt)
      })
    // //選択肢の際に参考
    // for (let i = 0; i < data.length; i++) {
    //   document.write(data[i] + ",");
    //   document.write("<BR>");
    // }


  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js PostgreSQL
        </h1>

        <p className={styles.description}>
          Next.js上でpostgresqlからデータ取得し、表示する例 <br />

        </p>

        <p>
          <strong>試験名</strong>：{examid} ; {examtitle}
        </p>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright 2021 m_sawada
        </a>
      </footer>
    </div >
  )
}